//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "design_transformer")]
	public partial class Design_transformer {

		/// <summary>
		/// 变压器设备ID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(32)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 方位角
		/// </summary>
		[JsonProperty, Column(Name = "azimuth")]
		public double? Azimuth { get; set; }

		/// <summary>
		/// 容量
		/// </summary>
		[JsonProperty, Column(Name = "capacity", DbType = "varchar(50)")]
		public string Capacity { get; set; } = string.Empty;

		/// <summary>
		/// 安装方式
		/// </summary>
		[JsonProperty, Column(Name = "fix_mode")]
		public int? Fix_mode { get; set; }

		/// <summary>
		/// 几何列，类型为点
		/// </summary>
		[JsonProperty, Column(Name = "geom")]
		public PostgisGeometry Geom { get; set; }

		/// <summary>
		/// 纬度
		/// </summary>
		[JsonProperty, Column(Name = "lat")]
		public double Lat { get; set; }

		/// <summary>
		/// 经度
		/// </summary>
		[JsonProperty, Column(Name = "lon")]
		public double Lon { get; set; }

		/// <summary>
		/// 主杆ID
		/// </summary>
		[JsonProperty, Column(Name = "main_id", DbType = "varchar(32)")]
		public string Main_id { get; set; } = string.Empty;

		/// <summary>
		/// 变压器型号
		/// </summary>
		[JsonProperty, Column(Name = "mode", DbType = "varchar(100)")]
		public string Mode { get; set; } = string.Empty;

		/// <summary>
		/// 型号ID
		/// </summary>
		[JsonProperty, Column(Name = "mode_id")]
		public string Mode_id { get; set; } = string.Empty;

		/// <summary>
		/// 变压器名称
		/// </summary>
		[JsonProperty, Column(Name = "name", DbType = "varchar(60)")]
		public string Name { get; set; } = string.Empty;

		/// <summary>
		/// 工程编号
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(Name = "remark", DbType = "varchar(50)")]
		public string Remark { get; set; } = string.Empty;

		/// <summary>
		/// 状态
		/// </summary>
		[JsonProperty, Column(Name = "state")]
		public int? State { get; set; }

		/// <summary>
		/// 副杆ID
		/// </summary>
		[JsonProperty, Column(Name = "sub_id", DbType = "varchar(32)")]
		public string Sub_id { get; set; } = string.Empty;

		/// <summary>
		/// 勘测时间
		/// </summary>
		[JsonProperty, Column(Name = "survey_time")]
		public DateTime? Survey_time { get; set; }

		/// <summary>
		/// 勘测人员
		/// </summary>
		[JsonProperty, Column(Name = "surveyor", DbType = "varchar(64)")]
		public string Surveyor { get; set; } = string.Empty;

		/// <summary>
		/// 符号ID
		/// </summary>
		[JsonProperty, Column(Name = "symbol_id")]
		public short? Symbol_id { get; set; }

	}

}
