//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "design_over_head_device")]
	public partial class Design_over_head_device {

		/// <summary>
		/// 杆上设备ID，主键，UUID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(64)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 方位角
		/// </summary>
		[JsonProperty, Column(Name = "azimuth")]
		public double? Azimuth { get; set; }

		/// <summary>
		/// 容量
		/// </summary>
		[JsonProperty, Column(Name = "capacity")]
		public string Capacity { get; set; } = string.Empty;

		/// <summary>
		/// 安装方法：无、电缆引下左侧装、电缆引下右侧装、架空引下正装、电缆引下正装、架空引下左侧装、架空引下右侧装
		/// </summary>
		[JsonProperty, Column(Name = "fix_mode")]
		public int? Fix_mode { get; set; }

		/// <summary>
		/// 几何列，类型为点
		/// </summary>
		[JsonProperty, Column(Name = "geom")]
		public PostgisGeometry Geom { get; set; }

		/// <summary>
		/// 纬度
		/// </summary>
		[JsonProperty, Column(Name = "lat")]
		public double? Lat { get; set; }

		/// <summary>
		/// 经度
		/// </summary>
		[JsonProperty, Column(Name = "lon")]
		public double? Lon { get; set; }

		/// <summary>
		/// 所属杆塔ID（主杆）
		/// </summary>
		[JsonProperty, Column(Name = "main_id", DbType = "varchar(64)")]
		public string Main_id { get; set; } = string.Empty;

		/// <summary>
		/// 型号
		/// </summary>
		[JsonProperty, Column(Name = "mode")]
		public string Mode { get; set; } = string.Empty;

		/// <summary>
		/// 型号ID
		/// </summary>
		[JsonProperty, Column(Name = "mode_id", DbType = "varchar(64)")]
		public string Mode_id { get; set; } = string.Empty;

		/// <summary>
		/// 设备名称
		/// </summary>
		[JsonProperty, Column(Name = "name")]
		public string Name { get; set; } = string.Empty;

		/// <summary>
		/// 所属工程ID
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(Name = "remark")]
		public string Remark { get; set; } = string.Empty;

		/// <summary>
		/// 状态：1-新建，2-利旧，3-原有，4-换装。枚举。在勘测表中，默认写入 新建
		/// </summary>
		[JsonProperty, Column(Name = "state")]
		public int? State { get; set; }

		/// <summary>
		/// 所属杆塔ID（副杆）
		/// </summary>
		[JsonProperty, Column(Name = "sub_id", DbType = "varchar(64)")]
		public string Sub_id { get; set; } = string.Empty;

		/// <summary>
		/// 勘测时间
		/// </summary>
		[JsonProperty, Column(Name = "survey_time")]
		public DateTime? Survey_time { get; set; }

		/// <summary>
		/// 勘测人员
		/// </summary>
		[JsonProperty, Column(Name = "surveyor", DbType = "varchar(64)")]
		public string Surveyor { get; set; } = string.Empty;

		/// <summary>
		/// 符号ID
		/// </summary>
		[JsonProperty, Column(Name = "symbol_id")]
		public short? Symbol_id { get; set; }

		/// <summary>
		/// 类型：变压器、熔断器、断路器、隔离刀闸、避雷器。枚举
		/// </summary>
		[JsonProperty, Column(Name = "type")]
		public int Type { get; set; }

	}

}
