//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "design_cable_equipment")]
	public partial class Design_cable_equipment {

		/// <summary>
		/// ID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(32)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 方位角
		/// </summary>
		[JsonProperty, Column(Name = "azimuth")]
		public double? Azimuth { get; set; }

		/// <summary>
		/// 容量
		/// </summary>
		[JsonProperty, Column(Name = "capacity", DbType = "varchar(32)")]
		public string Capacity { get; set; } = string.Empty;

		/// <summary>
		/// 设备编号
		/// </summary>
		[JsonProperty, Column(Name = "code", DbType = "varchar(60)")]
		public string Code { get; set; } = string.Empty;

		/// <summary>
		/// 型号
		/// </summary>
		[JsonProperty, Column(Name = "equip_model", DbType = "varchar(20)")]
		public string Equip_model { get; set; } = string.Empty;

		/// <summary>
		/// 型号ID
		/// </summary>
		[JsonProperty, Column(Name = "equip_model_id", DbType = "varchar(64)")]
		public string Equip_model_id { get; set; } = string.Empty;

		/// <summary>
		/// 几何列，类型为点
		/// </summary>
		[JsonProperty, Column(Name = "geom")]
		public PostgisGeometry Geom { get; set; }

		/// <summary>
		/// 高
		/// </summary>
		[JsonProperty, Column(Name = "height", DbType = "varchar(30)")]
		public string Height { get; set; } = string.Empty;

		/// <summary>
		/// 长
		/// </summary>
		[JsonProperty, Column(Name = "length", DbType = "varchar(30)")]
		public string Length { get; set; } = string.Empty;

		/// <summary>
		/// 逻辑编号
		/// </summary>
		[JsonProperty, Column(Name = "logic_code", DbType = "varchar(15)")]
		public string Logic_code { get; set; } = string.Empty;

		/// <summary>
		/// 设备名称
		/// </summary>
		[JsonProperty, Column(Name = "name", DbType = "varchar(60)")]
		public string Name { get; set; } = string.Empty;

		/// <summary>
		/// 上一节点ID
		/// </summary>
		[JsonProperty, Column(Name = "parent_id", DbType = "varchar(32)")]
		public string Parent_id { get; set; } = string.Empty;

		/// <summary>
		/// 上一节点类型
		/// </summary>
		[JsonProperty, Column(Name = "pre_node_type")]
		public int? Pre_node_type { get; set; }

		/// <summary>
		/// 工程编号
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(Name = "remark")]
		public string Remark { get; set; } = string.Empty;

		/// <summary>
		/// 状态
		/// </summary>
		[JsonProperty, Column(Name = "state")]
		public int? State { get; set; }

		/// <summary>
		/// 勘测时间
		/// </summary>
		[JsonProperty, Column(Name = "survey_time")]
		public DateTime? Survey_time { get; set; }

		/// <summary>
		/// 勘测人员
		/// </summary>
		[JsonProperty, Column(Name = "surveyor", DbType = "varchar(64)")]
		public string Surveyor { get; set; } = string.Empty;

		/// <summary>
		/// 符号ID
		/// </summary>
		[JsonProperty, Column(Name = "symbol_id")]
		public short? Symbol_id { get; set; }

		/// <summary>
		/// 设备类型
		/// </summary>
		[JsonProperty, Column(Name = "type")]
		public int? Type { get; set; }

		/// <summary>
		/// 宽
		/// </summary>
		[JsonProperty, Column(Name = "width", DbType = "varchar(30)")]
		public string Width { get; set; } = string.Empty;

	}

}
