//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "disclosure_track")]
	public partial class Disclosure_track {

		/// <summary>
		/// ID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(32)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 所属公司
		/// </summary>
		[JsonProperty, Column(Name = "company", DbType = "varchar(254)")]
		public string Company { get; set; } = string.Empty;

		/// <summary>
		/// 几何列
		/// </summary>
		[JsonProperty, Column(Name = "geom")]
		public PostgisGeometry Geom { get; set; }

		/// <summary>
		/// 工程编号
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 记录日期
		/// </summary>
		[JsonProperty, Column(Name = "record_date")]
		public DateTime? Record_date { get; set; }

		/// <summary>
		/// 记录者
		/// </summary>
		[JsonProperty, Column(Name = "recorder", DbType = "varchar(64)")]
		public string Recorder { get; set; } = string.Empty;

		/// <summary>
		/// 轨迹类型
		/// </summary>
		[JsonProperty, Column(Name = "type")]
		public int? Type { get; set; }

	}

}
