//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "dismantle_cable_channel_profile")]
	public partial class Dismantle_cable_channel_profile {

		/// <summary>
		/// 电缆通道ID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(64)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 列号
		/// </summary>
		[JsonProperty, Column(Name = "col")]
		public int? Col { get; set; }

		/// <summary>
		/// 所属设备ID
		/// </summary>
		[JsonProperty, Column(Name = "device_id", DbType = "varchar(64)")]
		public string Device_id { get; set; } = string.Empty;

		/// <summary>
		/// 所属工程ID
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 行号
		/// </summary>
		[JsonProperty, Column(Name = "row")]
		public int Row { get; set; }

		/// <summary>
		/// 符号ID
		/// </summary>
		[JsonProperty, Column(Name = "symbol_id")]
		public short? Symbol_id { get; set; }

		/// <summary>
		/// 通道使用状态
		/// </summary>
		[JsonProperty, Column(Name = "usage_state")]
		public int? Usage_state { get; set; }

	}

}
