//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "dismantle_cross_arm")]
	public partial class Dismantle_cross_arm {

		/// <summary>
		/// 横担ID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(32)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 方位角
		/// </summary>
		[JsonProperty, Column(Name = "azimuth")]
		public double? Azimuth { get; set; }

		/// <summary>
		/// 几何列，类型为点
		/// </summary>
		[JsonProperty, Column(Name = "geom")]
		public PostgisGeometry Geom { get; set; }

		/// <summary>
		/// 型号
		/// </summary>
		[JsonProperty, Column(Name = "model", DbType = "varchar(20)")]
		public string Model { get; set; } = string.Empty;

		/// <summary>
		/// 型号ID
		/// </summary>
		[JsonProperty, Column(Name = "model_id", DbType = "varchar(64)")]
		public string Model_id { get; set; } = string.Empty;

		/// <summary>
		/// 所属要素Id
		/// </summary>
		[JsonProperty, Column(Name = "parent_id", DbType = "varchar(32)")]
		public string Parent_id { get; set; } = string.Empty;

		/// <summary>
		/// 所属图层名称
		/// </summary>
		[JsonProperty, Column(Name = "parent_name", DbType = "varchar(32)")]
		public string Parent_name { get; set; } = string.Empty;

		/// <summary>
		/// 所属工程编号
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 状态
		/// </summary>
		[JsonProperty, Column(Name = "state")]
		public int? State { get; set; }

		/// <summary>
		/// 类型
		/// </summary>
		[JsonProperty, Column(Name = "type", DbType = "varchar(15)")]
		public string Type { get; set; } = string.Empty;

		/// <summary>
		/// 电压等级
		/// </summary>
		[JsonProperty, Column(Name = "voltage", DbType = "varchar(15)")]
		public string Voltage { get; set; } = string.Empty;

	}

}
