//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "dismantle_pull_line")]
	public partial class Dismantle_pull_line {

		/// <summary>
		/// 拉线ID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(32)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 方位角
		/// </summary>
		[JsonProperty, Column(Name = "azimuth")]
		public double? Azimuth { get; set; }

		/// <summary>
		/// 几何列，类型为点
		/// </summary>
		[JsonProperty, Column(Name = "geom")]
		public PostgisGeometry Geom { get; set; }

		/// <summary>
		/// 杆塔ID
		/// </summary>
		[JsonProperty, Column(Name = "main_id", DbType = "varchar(32)")]
		public string Main_id { get; set; } = string.Empty;

		/// <summary>
		/// 拉线型号
		/// </summary>
		[JsonProperty, Column(Name = "mode", DbType = "varchar(60)")]
		public string Mode { get; set; } = string.Empty;

		/// <summary>
		/// 拉线型号ID
		/// </summary>
		[JsonProperty, Column(Name = "mode_id", DbType = "varchar(64)")]
		public string Mode_id { get; set; } = string.Empty;

		/// <summary>
		/// 工程编号
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(Name = "remark")]
		public string Remark { get; set; } = string.Empty;

		/// <summary>
		/// 状态(0:无,1:原有,2:新建,3:利旧)
		/// </summary>
		[JsonProperty, Column(Name = "state")]
		public int? State { get; set; }

		/// <summary>
		/// 经度
		/// </summary>
		[JsonProperty, Column(Name = "lat")]
		public float Lat { get; set; }

		/// <summary>
		/// 维度
		/// </summary>
		[JsonProperty, Column(Name = "lon")]
		public float Lon { get; set; }
	}

}
