//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "survey_turning_points")]
	public partial class Survey_turning_points {

		/// <summary>
		/// 唯一ID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(32)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 多回路的线距离折点的距离
		/// </summary>
		[JsonProperty, Column(Name = "distance")]
		public double? Distance { get; set; }

		/// <summary>
		/// 所属线要素ID
		/// </summary>
		[JsonProperty, Column(Name = "geo_id", DbType = "text")]
		public string Geo_id { get; set; } = string.Empty;

		/// <summary>
		/// 所属线图层类型
		/// </summary>
		[JsonProperty, Column(Name = "geo_type", DbType = "text")]
		public string Geo_type { get; set; } = string.Empty;

		/// <summary>
		/// 折点序号
		/// </summary>
		[JsonProperty, Column(Name = "index")]
		public short? Index { get; set; }

		/// <summary>
		/// 折点关联的要素ID
		/// </summary>
		[JsonProperty, Column(Name = "node_id", DbType = "text")]
		public string Node_id { get; set; } = string.Empty;

		/// <summary>
		/// 折点关联的要素类型
		/// </summary>
		[JsonProperty, Column(Name = "node_type", DbType = "text")]
		public string Node_type { get; set; } = string.Empty;

		/// <summary>
		/// 项目ID
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 折点X坐标
		/// </summary>
		[JsonProperty, Column(Name = "x")]
		public double X { get; set; }

		/// <summary>
		/// 折点Y坐标
		/// </summary>
		[JsonProperty, Column(Name = "y")]
		public double Y { get; set; }

	}

}
