//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using System.Net;
using Newtonsoft.Json.Linq;
using System.Net.NetworkInformation;
using NpgsqlTypes;
using Npgsql.LegacyPostgis;

namespace GisModel {

	[JsonObject(MemberSerialization.OptIn), Table(Name = "survey_tower")]
	public partial class Survey_tower {

		/// <summary>
		/// 勘测杆塔ID，主键，UUID
		/// </summary>
		[JsonProperty, Column(Name = "id", DbType = "varchar(64)", IsPrimary = true)]
		public string Id { get; set; } = string.Empty;

		/// <summary>
		/// 方位角
		/// </summary>
		[JsonProperty, Column(Name = "azimuth")]
		public double? Azimuth { get; set; }

		/// <summary>
		/// 杆塔编号
		/// </summary>
		[JsonProperty, Column(Name = "code")]
		public string Code { get; set; } = string.Empty;

		/// <summary>
		/// 埋深
		/// </summary>
		[JsonProperty, Column(Name = "depth")]
		public double? Depth { get; set; }

		/// <summary>
		/// 带电作业
		/// </summary>
		[JsonProperty, Column(Name = "electrified_work")]
		public bool? Electrified_work { get; set; }

		/// <summary>
		/// 几何列，类型为点
		/// </summary>
		[JsonProperty, Column(Name = "geom")]
		public PostgisGeometry Geom { get; set; }

		/// <summary>
		/// 杆高
		/// </summary>
		[JsonProperty, Column(Name = "height", DbType = "varchar(20)")]
		public string Height { get; set; } = string.Empty;

		/// <summary>
		/// 是否耐张杆
		/// </summary>
		[JsonProperty, Column(Name = "is_tension")]
		public short? Is_tension { get; set; }

		/// <summary>
		/// 电压等级，枚举
		/// </summary>
		[JsonProperty, Column(Name = "kv_level")]
		public int Kv_level { get; set; }

		/// <summary>
		/// 纬度
		/// </summary>
		[JsonProperty, Column(Name = "lat")]
		public double Lat { get; set; }

		/// <summary>
		/// 联动回路数
		/// </summary>
		[JsonProperty, Column(Name = "link_num", DbType = "varchar(15)")]
		public string Link_num { get; set; } = string.Empty;

		/// <summary>
		/// 逻辑编号
		/// </summary>
		[JsonProperty, Column(Name = "logic_code", DbType = "varchar(15)")]
		public string Logic_code { get; set; } = string.Empty;

		/// <summary>
		/// 经度
		/// </summary>
		[JsonProperty, Column(Name = "lon")]
		public double Lon { get; set; }

		/// <summary>
		/// 回路层级
		/// </summary>
		[JsonProperty, Column(Name = "loop_level")]
		public string Loop_level { get; set; } = string.Empty;

		/// <summary>
		/// 回路名称
		/// </summary>
		[JsonProperty, Column(Name = "loop_name")]
		public string Loop_name { get; set; } = string.Empty;

		/// <summary>
		/// 回路数量
		/// </summary>
		[JsonProperty, Column(Name = "loop_num", DbType = "varchar(15)")]
		public string Loop_num { get; set; } = string.Empty;

		/// <summary>
		/// 杆材质，预留
		/// </summary>
		[JsonProperty, Column(Name = "material")]
		public string Material { get; set; } = string.Empty;

		/// <summary>
		/// 杆型方案，预留
		/// </summary>
		[JsonProperty, Column(Name = "mode")]
		public string Mode { get; set; } = string.Empty;

		/// <summary>
		/// 型号ID
		/// </summary>
		[JsonProperty, Column(Name = "mode_id", DbType = "varchar(64)")]
		public string Mode_id { get; set; } = string.Empty;

		/// <summary>
		/// 上一个杆塔ID
		/// </summary>
		[JsonProperty, Column(Name = "parent_id", DbType = "varchar(64)")]
		public string Parent_id { get; set; } = string.Empty;

		/// <summary>
		/// 杆型编号
		/// </summary>
		[JsonProperty, Column(Name = "pole_type_code", DbType = "varchar(20)")]
		public string Pole_type_code { get; set; } = string.Empty;

		/// <summary>
		/// 上一节点类型
		/// </summary>
		[JsonProperty, Column(Name = "pre_node_type")]
		public int? Pre_node_type { get; set; }

		/// <summary>
		/// 所属工程ID
		/// </summary>
		[JsonProperty, Column(Name = "project_id", DbType = "varchar(64)")]
		public string Project_id { get; set; } = string.Empty;

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(Name = "remark")]
		public string Remark { get; set; } = string.Empty;

		/// <summary>
		/// 杆梢径
		/// </summary>
		[JsonProperty, Column(Name = "rod", DbType = "varchar(20)")]
		public string Rod { get; set; } = string.Empty;

		/// <summary>
		/// 分段方式，预留
		/// </summary>
		[JsonProperty, Column(Name = "segment")]
		public int? Segment { get; set; }

		/// <summary>
		/// 排列方式，预留
		/// </summary>
		[JsonProperty, Column(Name = "sort")]
		public int? Sort { get; set; }

		/// <summary>
		/// 状态：1-新建，2-利旧，3-原有，4-换装。枚举。在勘测表中，默认写入 新建
		/// </summary>
		[JsonProperty, Column(Name = "state")]
		public int? State { get; set; }

		/// <summary>
		/// 勘测时间
		/// </summary>
		[JsonProperty, Column(Name = "survey_time")]
		public DateTime? Survey_time { get; set; }

		/// <summary>
		/// 勘测人员
		/// </summary>
		[JsonProperty, Column(Name = "surveyor", DbType = "varchar(64)")]
		public string Surveyor { get; set; } = string.Empty;

		/// <summary>
		/// 符号ID
		/// </summary>
		[JsonProperty, Column(Name = "symbol_id")]
		public short? Symbol_id { get; set; }

		/// <summary>
		/// 杆型，枚举
		/// </summary>
		[JsonProperty, Column(Name = "type")]
		public string Type { get; set; } = string.Empty;

	}

}
